import Nav from "./components/Nav";
import "./globals.css";
import { Poppins } from "next/font/google";
import GlobalProvider from "./components/context/global";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata = {
  title: "This is where you write the title of the docs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={poppins.className}>
          <Nav />
          {children}
        </body>
      </GlobalProvider>
    </html>
  );
}
